services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpass   # задайте свой пароль
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: rootpass          # тот же пароль, что выше
    ports:
      - "8080:80"